package it.alessandromencarini.droidtrailer;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import it.alessandromencarini.droidtrailer.PullRequest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PULL_REQUEST.
*/
public class PullRequestDao extends AbstractDao<PullRequest, Long> {

    public static final String TABLENAME = "PULL_REQUEST";

    /**
     * Properties of entity PullRequest.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property UserLogin = new Property(2, String.class, "userLogin", false, "USER_LOGIN");
        public final static Property State = new Property(3, String.class, "state", false, "STATE");
        public final static Property Url = new Property(4, String.class, "url", false, "URL");
        public final static Property UserAvatarUrl = new Property(5, String.class, "userAvatarUrl", false, "USER_AVATAR_URL");
        public final static Property Number = new Property(6, Integer.class, "number", false, "NUMBER");
        public final static Property CommentCount = new Property(7, Integer.class, "commentCount", false, "COMMENT_COUNT");
        public final static Property AssignedToMe = new Property(8, Boolean.class, "assignedToMe", false, "ASSIGNED_TO_ME");
        public final static Property Mergeable = new Property(9, Boolean.class, "mergeable", false, "MERGEABLE");
        public final static Property CreatedAt = new Property(10, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(11, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
        public final static Property ClosedAt = new Property(12, java.util.Date.class, "closedAt", false, "CLOSED_AT");
        public final static Property MergedAt = new Property(13, java.util.Date.class, "mergedAt", false, "MERGED_AT");
        public final static Property ReadAt = new Property(14, java.util.Date.class, "readAt", false, "READ_AT");
        public final static Property Participated = new Property(15, Boolean.class, "participated", false, "PARTICIPATED");
        public final static Property RepositoryId = new Property(16, long.class, "repositoryId", false, "REPOSITORY_ID");
    };

    private DaoSession daoSession;

    private Query<PullRequest> repository_PullRequestListQuery;

    public PullRequestDao(DaoConfig config) {
        super(config);
    }
    
    public PullRequestDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PULL_REQUEST' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TITLE' TEXT," + // 1: title
                "'USER_LOGIN' TEXT," + // 2: userLogin
                "'STATE' TEXT," + // 3: state
                "'URL' TEXT," + // 4: url
                "'USER_AVATAR_URL' TEXT," + // 5: userAvatarUrl
                "'NUMBER' INTEGER," + // 6: number
                "'COMMENT_COUNT' INTEGER," + // 7: commentCount
                "'ASSIGNED_TO_ME' INTEGER," + // 8: assignedToMe
                "'MERGEABLE' INTEGER," + // 9: mergeable
                "'CREATED_AT' INTEGER," + // 10: createdAt
                "'UPDATED_AT' INTEGER," + // 11: updatedAt
                "'CLOSED_AT' INTEGER," + // 12: closedAt
                "'MERGED_AT' INTEGER," + // 13: mergedAt
                "'READ_AT' INTEGER," + // 14: readAt
                "'PARTICIPATED' INTEGER," + // 15: participated
                "'REPOSITORY_ID' INTEGER NOT NULL );"); // 16: repositoryId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PULL_REQUEST'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PullRequest entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String userLogin = entity.getUserLogin();
        if (userLogin != null) {
            stmt.bindString(3, userLogin);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(4, state);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(5, url);
        }
 
        String userAvatarUrl = entity.getUserAvatarUrl();
        if (userAvatarUrl != null) {
            stmt.bindString(6, userAvatarUrl);
        }
 
        Integer number = entity.getNumber();
        if (number != null) {
            stmt.bindLong(7, number);
        }
 
        Integer commentCount = entity.getCommentCount();
        if (commentCount != null) {
            stmt.bindLong(8, commentCount);
        }
 
        Boolean assignedToMe = entity.getAssignedToMe();
        if (assignedToMe != null) {
            stmt.bindLong(9, assignedToMe ? 1l: 0l);
        }
 
        Boolean mergeable = entity.getMergeable();
        if (mergeable != null) {
            stmt.bindLong(10, mergeable ? 1l: 0l);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(11, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(12, updatedAt.getTime());
        }
 
        java.util.Date closedAt = entity.getClosedAt();
        if (closedAt != null) {
            stmt.bindLong(13, closedAt.getTime());
        }
 
        java.util.Date mergedAt = entity.getMergedAt();
        if (mergedAt != null) {
            stmt.bindLong(14, mergedAt.getTime());
        }
 
        java.util.Date readAt = entity.getReadAt();
        if (readAt != null) {
            stmt.bindLong(15, readAt.getTime());
        }
 
        Boolean participated = entity.getParticipated();
        if (participated != null) {
            stmt.bindLong(16, participated ? 1l: 0l);
        }
        stmt.bindLong(17, entity.getRepositoryId());
    }

    @Override
    protected void attachEntity(PullRequest entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PullRequest readEntity(Cursor cursor, int offset) {
        PullRequest entity = new PullRequest( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userLogin
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // state
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // url
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // userAvatarUrl
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // number
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // commentCount
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // assignedToMe
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // mergeable
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // createdAt
            cursor.isNull(offset + 11) ? null : new java.util.Date(cursor.getLong(offset + 11)), // updatedAt
            cursor.isNull(offset + 12) ? null : new java.util.Date(cursor.getLong(offset + 12)), // closedAt
            cursor.isNull(offset + 13) ? null : new java.util.Date(cursor.getLong(offset + 13)), // mergedAt
            cursor.isNull(offset + 14) ? null : new java.util.Date(cursor.getLong(offset + 14)), // readAt
            cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0, // participated
            cursor.getLong(offset + 16) // repositoryId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PullRequest entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserLogin(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setState(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserAvatarUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setNumber(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setCommentCount(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setAssignedToMe(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setMergeable(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setCreatedAt(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setUpdatedAt(cursor.isNull(offset + 11) ? null : new java.util.Date(cursor.getLong(offset + 11)));
        entity.setClosedAt(cursor.isNull(offset + 12) ? null : new java.util.Date(cursor.getLong(offset + 12)));
        entity.setMergedAt(cursor.isNull(offset + 13) ? null : new java.util.Date(cursor.getLong(offset + 13)));
        entity.setReadAt(cursor.isNull(offset + 14) ? null : new java.util.Date(cursor.getLong(offset + 14)));
        entity.setParticipated(cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0);
        entity.setRepositoryId(cursor.getLong(offset + 16));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PullRequest entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PullRequest entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "pullRequestList" to-many relationship of Repository. */
    public List<PullRequest> _queryRepository_PullRequestList(long repositoryId) {
        synchronized (this) {
            if (repository_PullRequestListQuery == null) {
                QueryBuilder<PullRequest> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RepositoryId.eq(null));
                repository_PullRequestListQuery = queryBuilder.build();
            }
        }
        Query<PullRequest> query = repository_PullRequestListQuery.forCurrentThread();
        query.setParameter(0, repositoryId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getRepositoryDao().getAllColumns());
            builder.append(" FROM PULL_REQUEST T");
            builder.append(" LEFT JOIN REPOSITORY T0 ON T.'REPOSITORY_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PullRequest loadCurrentDeep(Cursor cursor, boolean lock) {
        PullRequest entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Repository repository = loadCurrentOther(daoSession.getRepositoryDao(), cursor, offset);
         if(repository != null) {
            entity.setRepository(repository);
        }

        return entity;    
    }

    public PullRequest loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PullRequest> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PullRequest> list = new ArrayList<PullRequest>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PullRequest> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PullRequest> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
